version: 0.2.0.{build}
os: Visual Studio 2015
install:
- cmd: nuget install redis-64 -OutputDirectory packages -excludeversion 
- cmd: packages\redis-64\tools\redis-server.exe --service-install
- cmd: packages\redis-64\tools\redis-server.exe --service-start
test: off
build_script:
- cmd: build.cmd ci
artifacts:
  - path: './bin/*.zip'
    name: ProjectScaffolding
cache:
- packages -> **\packages.config
